class atom:
    @classmethod
    def __init__(cls, *args, **kwargs) -> None: ...
    def pack(self, *args, **kwargs): ...
    def size(self, *args, **kwargs): ...
    def type(self, *args, **kwargs): ...
    def unpack(self, *args, **kwargs): ...
