# Copyright (C) MatrixEditor 2023-2026
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
from ._base import DEFAULT_OPTION, INVALID_DEFAULT, Field, singleton
from ._mixin import (Chain, FieldMixin, FieldStruct, Operator, get_args,
                     get_kwargs)
from .common import (ENUM_STRICT, Aligned, AsLengthRef, Bytes, Computed, Const,
                     ConstBytes, ConstString, CString, Enum, Int, Lazy, Memory,
                     Padded, Padding, Pass, PostPad, Prefixed, PrePad,
                     PyStructFormattedField, String, Timestamp, Transformer,
                     UInt, Uuid, align, boolean, char, double, float16,
                     float32, float64, int8, int16, int24, int32, int64,
                     padding, psize, pssize, uint8, uint16, uint24, uint32,
                     uint64, void_ptr)
from .compression import (Bz2Compressed, Compressed, LZMACompressed,
                          LZOCompressed, ZLibCompressed)
from .conditional import (Branch, ConditionalChain, Else, ElseIf, End, If,
                          Otherwise, Start, When)
from .crypto import And, Encrypted, KeyCipher, Or, Xor
from .digest import (CTX_DIGEST, CTX_DIGEST_ALGO, CTX_DIGEST_HOOK,
                     CTX_DIGEST_OBJ, HMAC, Adler, Adler_Algo, Adler_Field,
                     Algorithm, Crc32, Crc32_Algo, Crc32_Field, Digest,
                     DigestField, DigestFieldAction, HMACAlgorithm, Md5,
                     Md5_Algo, Md5_Field, Sha1, Sha1_Algo, Sha1_Field,
                     Sha2_224, Sha2_224_Algo, Sha2_224_Field, Sha2_256,
                     Sha2_256_Algo, Sha2_256_Field, Sha2_384, Sha2_384_Algo,
                     Sha2_384_Field, Sha2_512, Sha2_512_Algo, Sha2_512_Field,
                     Sha3_224, Sha3_224_Algo, Sha3_224_Field, Sha3_256,
                     Sha3_256_Algo, Sha3_256_Field, Sha3_384, Sha3_384_Algo,
                     Sha3_384_Field, Sha3_512, Sha3_512_Algo, Sha3_512_Field)
from .hook import IOHook
from .net import MAC, IPv4Address, IPv6Address, MACAddress
from .pointer import (PTR_STRICT, Pointer, RelativePointer, intptr, intptr_fn,
                      offintptr, offuintptr, pointer, relative_pointer,
                      uintptr, uintptr_fn)
from .varint import VARINT_LSB, VarInt, vint

__all__ = [
    "Adler_Algo",
    "Adler_Field",
    "Adler",
    "Algorithm",
    "align",
    "Aligned",
    "And",
    "AsLengthRef",
    "boolean",
    "Branch",
    "Bytes",
    "Bz2Compressed",
    "Chain",
    "char",
    "Compressed",
    "Computed",
    "ConditionalChain",
    "Const",
    "ConstBytes",
    "ConstString",
    "Crc32_Algo",
    "Crc32_Field",
    "Crc32",
    "CString",
    "CTX_DIGEST_ALGO",
    "CTX_DIGEST_HOOK",
    "CTX_DIGEST_OBJ",
    "CTX_DIGEST",
    "DEFAULT_OPTION",
    "Digest",
    "DigestField",
    "DigestFieldAction",
    "double",
    "Else",
    "ElseIf",
    "Encrypted",
    "End",
    "ENUM_STRICT",
    "Enum",
    "Field",
    "FieldMixin",
    "FieldStruct",
    "float16",
    "float32",
    "float64",
    "get_args",
    "get_kwargs",
    "HMAC",
    "HMACAlgorithm",
    "If",
    "Int",
    "int16",
    "int24",
    "int32",
    "int64",
    "int8",
    "intptr_fn",
    "intptr",
    "INVALID_DEFAULT",
    "IOHook",
    "IPv4Address",
    "IPv6Address",
    "KeyCipher",
    "Lazy",
    "LZMACompressed",
    "LZOCompressed",
    "MAC",
    "MACAddress",
    "Md5_Algo",
    "Md5_Field",
    "Md5",
    "Memory",
    "offintptr",
    "offuintptr",
    "Operator",
    "Or",
    "Otherwise",
    "Padded",
    "padding",
    "Padding",
    "Pass",
    "pointer",
    "Pointer",
    "PostPad",
    "Prefixed",
    "PrePad",
    "psize",
    "pssize",
    "PTR_STRICT",
    "PyStructFormattedField",
    "relative_pointer",
    "RelativePointer",
    "Sha1_Algo",
    "Sha1_Field",
    "Sha1",
    "Sha2_224_Algo",
    "Sha2_224_Field",
    "Sha2_224",
    "Sha2_256_Algo",
    "Sha2_256_Field",
    "Sha2_256",
    "Sha2_384_Algo",
    "Sha2_384_Field",
    "Sha2_384",
    "Sha2_512_Algo",
    "Sha2_512_Field",
    "Sha2_512",
    "Sha3_224_Algo",
    "Sha3_224_Field",
    "Sha3_224",
    "Sha3_256_Algo",
    "Sha3_256_Field",
    "Sha3_256",
    "Sha3_384_Algo",
    "Sha3_384_Field",
    "Sha3_384",
    "Sha3_512_Algo",
    "Sha3_512_Field",
    "Sha3_512",
    "singleton",
    "Start",
    "String",
    "Timestamp",
    "Transformer",
    "UInt",
    "uint16",
    "uint24",
    "uint32",
    "uint64",
    "uint8",
    "uintptr_fn",
    "uintptr",
    "Uuid",
    "VARINT_LSB",
    "VarInt",
    "vint",
    "void_ptr",
    "When",
    "Xor",
    "ZLibCompressed",
]
