name: Build and Deploy Docs

on:
  push:
    branches: ["master"]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r docs/requirements.txt && pip install -r requirements.txt && pip install -e .

      - name: Install doxygen
        run: |
           wget https://github.com/doxygen/doxygen/releases/download/Release_1_10_0/doxygen-1.10.0.linux.bin.tar.gz
           tar xzvf doxygen-1.10.0.linux.bin.tar.gz
           cd doxygen-1.10.0
           sudo make install
           cd ..
           rm -rf doxygen-1.10.0*

      - name: Build
        # Create .nojekyll file to disable Jekyll processing
        run: |
          cd docs/sphinx
          make html
          touch build/html/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/sphinx/build/html